'use client';

import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/lib/hooks/useAuth';
import { 
  ShoppingCart, 
  CheckCircle, 
  Clock, 
  Loader2,
  Package,
  Building2,
  AlertCircle,
  Sparkles
} from 'lucide-react';

interface PurchaseOrder {
  id: string;
  quantityOrdered: number;
  unitCost: number;
  status: string;
  createdBy: string;
  createdAt: string;
  item: {
    name: string;
    sku: string;
  };
  supplier: {
    name: string;
  };
}

export default function PurchaseOrdersPage() {
  const { token } = useAuth();
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const fetchOrders = useCallback(async () => {
    try {
      const res = await fetch('/api/purchase-orders', {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) {
        const data = await res.json();
        setOrders(data.purchaseOrders || []);
      }
    } catch (error) {
      console.error('Failed to fetch purchase orders:', error);
    }
    setLoading(false);
  }, [token]);

  useEffect(() => {
    if (token) {
      fetchOrders();
    }
  }, [token, fetchOrders]);

  const handleAction = async (poId: string, action: 'APPROVE' | 'REJECT') => {
    setActionLoading(poId);
    try {
      const res = await fetch('/api/purchase-orders', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}` 
        },
        body: JSON.stringify({ poId, action })
      });
      
      if (res.ok) {
        await fetchOrders();
      } else {
        alert('Failed to process action');
      }
    } catch (error) {
      console.error('Error processing PO:', error);
      alert('An error occurred');
    }
    setActionLoading(null);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  const pendingOrders = orders.filter(o => o.status === 'PENDING_APPROVAL');
  const historyOrders = orders.filter(o => o.status !== 'PENDING_APPROVAL');

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-headline font-bold text-on-surface">Purchase Orders</h1>
          <p className="text-on-surface-variant mt-1">Review AI-generated restock recommendations</p>
        </div>
      </div>

      {pendingOrders.length > 0 && (
        <div className="bg-primary-container/20 border border-primary/20 rounded-3xl p-6">
          <div className="flex items-center gap-3 mb-6">
            <AlertCircle className="text-primary w-6 h-6" />
            <h2 className="text-xl font-bold text-on-surface">Requires Your Approval</h2>
          </div>
          
          <div className="grid gap-4">
            {pendingOrders.map(order => (
              <div key={order.id} className="bg-surface rounded-2xl p-6 border border-outline-variant/30 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-sm">
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 rounded-xl bg-surface-container flex items-center justify-center shrink-0">
                    <ShoppingCart className="w-6 h-6 text-on-surface-variant" />
                  </div>
                  <div>
                    <h3 className="font-bold text-lg text-on-surface">{order.item.name}</h3>
                    <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-2 text-sm text-on-surface-variant">
                      <span className="flex items-center gap-1"><Package className="w-4 h-4" /> Qty: {order.quantityOrdered}</span>
                      <span className="flex items-center gap-1"><Building2 className="w-4 h-4" /> {order.supplier.name}</span>
                      <span className="font-mono bg-surface-container px-2 py-0.5 rounded text-xs">Total: ${(order.quantityOrdered * order.unitCost).toFixed(2)}</span>
                    </div>
                    {order.createdBy === 'AI_AGENT' && (
                      <div className="mt-3 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-tertiary-container/50 text-tertiary text-xs font-bold">
                        <Sparkles className="w-3 h-3" /> Auto-generated by AI
                      </div>
                    )}
                  </div>
                </div>
                
                <div className="flex items-center gap-3 w-full md:w-auto">
                  <button 
                    onClick={() => handleAction(order.id, 'REJECT')}
                    disabled={actionLoading === order.id}
                    className="flex-1 md:flex-none px-4 py-2 rounded-xl border border-error/30 text-error font-bold hover:bg-error/10 transition-colors disabled:opacity-50"
                  >
                    Reject
                  </button>
                  <button 
                    onClick={() => handleAction(order.id, 'APPROVE')}
                    disabled={actionLoading === order.id}
                    className="flex-1 md:flex-none px-6 py-2 rounded-xl bg-primary text-on-primary font-bold hover:bg-primary/90 transition-colors shadow-md shadow-primary/20 disabled:opacity-50 flex items-center justify-center gap-2"
                  >
                    {actionLoading === order.id ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle className="w-4 h-4" />}
                    Approve & Order
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div>
        <h2 className="text-xl font-bold text-on-surface mb-6">Order History</h2>
        {historyOrders.length === 0 ? (
          <div className="text-center py-12 bg-surface-container-low rounded-3xl border border-outline-variant/20 border-dashed">
            <Clock className="w-12 h-12 text-on-surface-variant/50 mx-auto mb-4" />
            <h3 className="text-lg font-bold text-on-surface">No order history</h3>
            <p className="text-on-surface-variant">Approved and rejected orders will appear here.</p>
          </div>
        ) : (
          <div className="bg-surface rounded-3xl border border-outline-variant/20 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-outline-variant/20 bg-surface-container-low/50">
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Item</th>
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Supplier</th>
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Qty</th>
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Total</th>
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Status</th>
                    <th className="p-4 font-bold text-sm text-on-surface-variant">Date</th>
                  </tr>
                </thead>
                <tbody>
                  {historyOrders.map((order) => (
                    <tr key={order.id} className="border-b border-outline-variant/10 hover:bg-surface-container-low/30 transition-colors">
                      <td className="p-4">
                        <div className="font-bold text-on-surface">{order.item.name}</div>
                        <div className="text-xs text-on-surface-variant font-mono">{order.item.sku}</div>
                      </td>
                      <td className="p-4 text-on-surface-variant">{order.supplier.name}</td>
                      <td className="p-4 font-mono text-on-surface">{order.quantityOrdered}</td>
                      <td className="p-4 font-mono text-on-surface">${(order.quantityOrdered * order.unitCost).toFixed(2)}</td>
                      <td className="p-4">
                        <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold ${
                          order.status === 'APPROVED' ? 'bg-primary/10 text-primary' : 'bg-error/10 text-error'
                        }`}>
                          {order.status}
                        </span>
                      </td>
                      <td className="p-4 text-sm text-on-surface-variant">
                        {new Date(order.createdAt).toLocaleDateString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
